#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 24 13:18:54 2020

@author: jd
"""
Clase 24/07
#Tuplas 
abarrotes= "leche,, café, arroz, azucar,, harina"
abarrotes = abarrotes.split(",")
print(abarrotes)
